### ISSUE TITLE
start / end parameters in Range are in opposite order

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/metricminer2#30]
just switch it

**Comment by nascimentolwtn** [comment]
Does the `RangeTest.should_get_commits_in_range()` method is passing for you? Shouldn't the parameters in test be swapped or the logic inside `Range.get()`?

**Comment by mauricioaniche** [comment]
Hmm, yes, that's a bug. And it's harder than it looks like. This `Range` class was completely dependent on the order of the list. Now, I made the algorithm a bit smarter in there.

Can you check the PR #36, @nascimentolwtn, @sandervdo ? If you say it's ok, I'll merge it!
